# Generated by Django 5.2.17 on 2026-09-24 17:00

import django.core.validators
import django.db.models.deletion
import tracker.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_reporter', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('has_consented', models.BooleanField(default=False, help_text='Reporter confirms they have read the consent information, are 13 or older, and agree to participate.')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], db_index=True, max_length=2)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_precision', models.CharField(choices=[('exact', 'Exact date'), ('month', 'Month and year'), ('ongoing', 'Ongoing'), ('unknown', 'Best estimate / unknown')], default='exact', max_length=20)),
                ('incident_date', models.DateField(blank=True, help_text='Used when a specific date is known.', null=True)),
                ('incident_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('incident_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)])),
                ('description', models.TextField()),
                ('city', models.CharField(blank=True, max_length=150)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('anti_palestinian_racism', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], db_index=True, max_length=10)),
                ('knows_of_other_apr_incidents', models.BooleanField(blank=True, help_text='Aside from this incident, does the respondent know of other incidents of anti-Palestinian racism?', null=True)),
                ('similar_incidents', models.CharField(blank=True, choices=[('dont_know', "Don't know"), ('never', 'Never'), ('once', 'Once'), ('occasionally', 'Occasionally'), ('frequently', 'Frequently')], db_index=True, max_length=20)),
                ('previously_reported', models.BooleanField(blank=True, help_text='For respondents for whom the general reporting question applies.', null=True)),
                ('resolution_steps', models.TextField(blank=True, help_text='Steps taken to resolve the issue before or aside from filing a complaint.')),
                ('connection_change', models.CharField(blank=True, choices=[('less', 'I feel less connected'), ('more', 'I feel more connected'), ('no_change', 'It did not change my connection'), ('not_applicable', 'Not applicable')], db_index=True, max_length=20)),
                ('other_identity_information', models.TextField(blank=True)),
                ('additional_information', models.TextField(blank=True)),
                ('support_sought_elsewhere', models.TextField(blank=True, help_text='Organizations, institutions, or attorneys from whom the respondent has sought support.')),
                ('opt_out_of_followup', models.BooleanField(default=False, help_text='Primarily used for non-California respondents who opt out of private follow-up questions or clarification.')),
                ('signature_name', models.CharField(blank=True, max_length=200)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AffectedPersonDemographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Nonbinary / gender expansive'), ('other', 'Other'), ('prefer_not', 'Prefer not to answer')], db_index=True, max_length=30)),
                ('gender_other', models.CharField(blank=True, max_length=150)),
                ('religion', models.CharField(blank=True, choices=[('buddhism', 'Buddhism'), ('christianity', 'Christianity'), ('hinduism', 'Hinduism'), ('islam', 'Islam'), ('judaism', 'Judaism'), ('sikhism', 'Sikhism'), ('taoism', 'Taoism'), ('none', 'None / no faith tradition'), ('other', 'Other'), ('prefer_not', 'Prefer not to say')], db_index=True, max_length=30)),
                ('religion_other', models.CharField(blank=True, max_length=150)),
                ('affected_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='tracker.affectedperson')),
            ],
        ),
        migrations.CreateModel(
            name='FormalSchoolComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previously_submitted_to_district', models.BooleanField(blank=True, db_index=True, null=True)),
                ('authorize_autopopulation', models.BooleanField(blank=True, help_text='Respondent authorizes the form to populate a formal complaint to the district authority or state.', null=True)),
                ('complaint_against', models.TextField(blank=True, help_text='Name, job title, school, department, or other identifying information for the person/entity complained against.')),
                ('individuals_involved', models.TextField(blank=True)),
                ('witnesses', models.TextField(blank=True)),
                ('discussed_with_principal_or_supervisor', models.BooleanField(blank=True, db_index=True, null=True)),
                ('concerns_addressed_to', models.CharField(blank=True, max_length=255)),
                ('concerns_addressed_date', models.DateField(blank=True, null=True)),
                ('requested_remedy', models.TextField(blank=True)),
                ('complainant_address', models.TextField(blank=True, help_text='Full address including apartment/unit number when required for submitting a formal complaint.')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formal_school_complaint', to='tracker.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='CaliforniaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_k12_incident', models.BooleanField(blank=True, db_index=True, help_text='Incident related to a California K-12 school system or affecting someone in that age range.', null=True)),
                ('reporter_role', models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('parent', 'Parent / Guardian'), ('student', 'Student'), ('admin', 'School administrator or staff'), ('education_org', 'Education organization staff'), ('other', 'Other')], db_index=True, max_length=30)),
                ('reporter_role_other', models.CharField(blank=True, max_length=200)),
                ('student_date_of_birth', models.DateField(blank=True, null=True)),
                ('child_full_name', models.CharField(blank=True, max_length=200)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='california_details', to='tracker.incidentreport')),
            ],
        ),
        migrations.AddField(
            model_name='affectedperson',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affected_person', to='tracker.incidentreport'),
        ),
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tracker.models.report_attachment_upload_to)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tracker.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('racism_type', 'Form of racism'), ('location_type', 'Location type'), ('incident_type', 'Incident type'), ('educational_impact', 'Educational impact'), ('wellbeing_impact', 'Well-being impact'), ('discrimination_experience', 'Discrimination experience'), ('targeted_identity', 'Targeted identity'), ('race_ethnicity', 'Race / ethnicity'), ('arab_palestinian_identity', 'Arab / Palestinian identity'), ('nonreport_reason', 'Reason incident was not reported')], db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('allows_other_text', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'label'],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='unique_report_option_category_slug')],
            },
        ),
        migrations.CreateModel(
            name='SchoolIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255)),
                ('school_district', models.CharField(blank=True, max_length=255)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('principal', models.CharField(blank=True, max_length=200)),
                ('location_within_school', models.CharField(blank=True, max_length=255)),
                ('school_type', models.CharField(blank=True, choices=[('public', 'Public'), ('private_secular', 'Private — Secular'), ('private_religious', 'Private — Religious / Parochial'), ('charter', 'Charter'), ('other', 'Other')], db_index=True, max_length=30)),
                ('school_type_other', models.CharField(blank=True, max_length=200)),
                ('school_was_aware', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], db_index=True, max_length=10)),
                ('concerns_addressed_to', models.CharField(blank=True, max_length=255)),
                ('concerns_addressed_date', models.DateField(blank=True, null=True)),
                ('teacher_admin_response', models.TextField(blank=True)),
                ('satisfied_with_response', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], db_index=True, max_length=10)),
                ('satisfaction_explanation', models.TextField(blank=True)),
                ('school_response_effect', models.CharField(blank=True, choices=[('improved', 'Improved'), ('worsened', 'Worsened'), ('no_change', 'No change'), ('unsure', 'Unsure')], db_index=True, max_length=20)),
                ('absence_due_to_racism_frequency', models.CharField(blank=True, choices=[('never', 'Never'), ('once', 'Once'), ('few_times', 'A few times'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('more_than_weekly', 'More than weekly')], db_index=True, max_length=30)),
                ('educational_requirement_violated', models.TextField(blank=True, help_text='Educational or program requirement the respondent believes was violated.')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_incident', to='tracker.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportOptionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_text', models.CharField(blank=True, max_length=500)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selections', to='tracker.reportoption')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_selections', to='tracker.incidentreport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'option'), name='unique_report_option_selection')],
            },
        ),
        migrations.CreateModel(
            name='ReportReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit', models.BooleanField(default=True)),
                ('anonymous', models.BooleanField(default=False, help_text='Share anonymized incident information only, without individual follow-up.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_referrals', to='tracker.referralorganization')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tracker.incidentreport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'organization'), name='unique_report_referral')],
            },
        ),
    ]
